### ISSUE TITLE
Use Bootstrap in Persons Page

### ISSUE THREAD

**Issue by BenWong1097** [SaltyQuetzals/CSCE-315-Team-3#54]
# Description

## Overview
Use styling provided by Bootstrap in the Persons Page

## Background
To make the design and user experience of the website more consistent and intuitive

## Tasks
- [ ] Include bootstrap in the page
- [ ] Create card objects for Movies
- [ ] Create left and right content sections

## Points
2.5
