### ISSUE TITLE
Use Bootstrap in Home Page

### ISSUE THREAD

**Issue by BenWong1097** [SaltyQuetzals/CSCE-315-Team-3#55]
# Description

## Overview
Use styling provided by Bootstrap in the Home Page

## Background
To make the design and user experience of the website more consistent and intuitive

## Tasks
- [ ] Include bootstrap in the page
- [ ] Create card objects for Persons Page
- [ ] Style each content section in bootstrap

## Points
2.5
