### ISSUE TITLE
Use Bootstrap in Movies Page

### ISSUE THREAD

**Issue by BenWong1097** [SaltyQuetzals/CSCE-315-Team-3#56]
# Description

## Overview
Use styling provided by Bootstrap in the Movies Page

## Background
To make the design and user experience of the website more consistent and intuitive

## Tasks
- [ ] Include bootstrap in the page
- [ ] Create card objects for People
- [ ] Style left and right content sections
- [ ] Style links
## Points
2.5
