### ISSUE TITLE
Use Bootstrap in Search Results Page

### ISSUE THREAD

**Issue by BenWong1097** [SaltyQuetzals/CSCE-315-Team-3#57]
# Description

## Overview
Use styling provided by Bootstrap in the Search Results Page

## Background
To make the design and user experience of the website more consistent and intuitive

## Tasks
- [ ] Include bootstrap in the page
- [ ] Create card objects for Movies
- [ ] Create card objects for Persons
- [ ] Style one overall search results section
- [ ] Differentiate between movies and persons
- [ ] Style links
## Points
2.5
