### ISSUE TITLE
Add clickable pictures

### ISSUE THREAD

**Issue by BenWong1097** [SaltyQuetzals/CSCE-315-Team-3#58]
# Description

## Overview
Allow for users to be redirected to the respectable person/movie when their picture is clicked.

## Background
To make the UI more intuitive.

## Tasks
- [x] Add the appropriate link to the Person pictures in the Movies page
- [x] Add the appropriate link to the Movie pictures in the Persons page
- [x] Add the appropriate link to the Person pictures in the Home page
- [x] Add the appropriate link to the Movie/Person pictures in the Search Results page
## Estimated Points/Man Hours
1

**Comment by ZihaoPTS** [comment]
Done

**Comment by SaltyQuetzals** [comment]
Closed by #65
