### ISSUE TITLE
Search interface on every page

### ISSUE THREAD

**Issue by Justin-Teng** [SaltyQuetzals/CSCE-315-Team-3#59]
# Description

## Overview
Add Search bar and button on every page.

## Background
For better user experience and convenience.

## Tasks
- [x] Add search interface to Results page.
- [x] Add search interface to Movie page.
- [x] Add search interface to Person page.
