### ISSUE TITLE
Movie Sorting

### ISSUE THREAD

**Issue by Justin-Teng** [SaltyQuetzals/CSCE-315-Team-3#60]
# Description

## Overview
Enable sorting on Movie page based on last name + first name, department, or character.

## Background
User experience.

## Tasks
- [ ] Enable sorting on Movie page based on last name + first name.
- [ ] Enable sorting on Movie page based on department.
- [ ] Enable sorting on Movie page based on character.

## Estimated Points/Man Hours
<estimated points/man hours>
