### ISSUE TITLE
Expandable Grid

### ISSUE THREAD

**Issue by BenWong1097** [SaltyQuetzals/CSCE-315-Team-3#61]
# Description

## Overview
Allow users to click on a button to reveal more entries

## Background
To not flood the page with information that might be irrelevant to the user

## Tasks
- [ ] Implement expandable grid
- [ ] Add grid to Persons page
- [ ] Add grid to Movies page

## Estimated Points/Man Hours
2
