### ISSUE TITLE
Person Page Sorting

### ISSUE THREAD

**Issue by Justin-Teng** [SaltyQuetzals/CSCE-315-Team-3#62]
# Description

## Overview
Enable sorting on Person page based on year, genre, or popularity.

## Background
User experience.

## Tasks
- [ ] Enable sorting on Person page based on year.
- [ ] Enable sorting on Person page based on genre.
- [ ] Enable sorting on Person page based on popularity.
- [ ] Make one sort filter the default.

## Estimated Points/Man Hours
<estimated points/man hours>
