### ISSUE TITLE
Connect MongoDB to Elasticsearch to improve search

### ISSUE THREAD

**Issue by SaltyQuetzals** [SaltyQuetzals/CSCE-315-Team-3#63]
# Description

## Overview
Using [`mongoose-elasticsearch-xp`](https://github.com/jbdemonte/mongoose-elasticsearch-xp) to improve search functionality.

## Background
Because of the new requirements set out by Dr. Kerne, we need to improve the search functionality of the application. We decided to use [Elasticsearch](https://www.elastic.co/) to leverage the advanced searching functionality that it provides, such as partial-text matching, fuzzy searching, n-gram searching, and more. 

## Tasks
- [X] Download Elasticsearch
- [X] Download [`mongoose-elasticsearch-xp`](https://github.com/jbdemonte/mongoose-elasticsearch-xp)
- [X] Index the existing data into Elasticsearch
- [X] Consolidate the results into one `results` array, sorted in decreasing order (highest-relevance first)
- [X] Ensure results are same format as before, with the exception of a `type` variable (`movie` or `person`)

## Estimated Points/Man Hours
3

**Comment by SaltyQuetzals** [comment]
Closed by #64
