### ISSUE TITLE
Add user authentication

### ISSUE THREAD

**Issue by SaltyQuetzals** [SaltyQuetzals/CSCE-315-Team-3#67]
# Description

## Overview
Creating user authentication so that users can "favorite" movies and actors, using Google OAuth2.0 protocol.

## Background
We'll need authentication to provide a convenient and quick way for users to view movies and actors that they actually care about, instead of all of the search results at once, which is inefficient and frustrating.

## Tasks
- [ ] Install and set up [Passport Google OAuth](https://github.com/jaredhanson/passport-google-oauth)
- [ ] Create the required credentials for Google OAuth2.0 on Google Developer's API Dashboard.
- [ ] Add permissions to the API on the endpoints that only authenticated users should be able to access.

## Estimated Points/Man Hours
3
