### ISSUE TITLE
Local Authentication Service

### ISSUE THREAD

**Issue by ZihaoPTS** [SaltyQuetzals/CSCE-315-Team-3#72]
# Since Google Auth require public domain name, we are moving to local authentication by passport

## Overview
Set up and Username/Password authentication functionality for the website so user will able to login and record their "liked movie"

## Background
User experience support

## Tasks
- [ ] Add back end functions that allow user to create & store password/Username
- [ ] Add back end functions that allow the authenticating user input information
- [ ] Add front end block for login

## Estimated Points/Man Hours
3.5
